### ISSUE TITLE
Including aws-sdk

### ISSUE THREAD

**Issue by maitriyogin** [webpack-contrib/script-loader#12]
Hi,
I'm trying to include a pre-built aws-sdk.js file into my bundle as a script.
My idea is to have a vendor dir which will contain all un-npm js, which I can just include with the script loader. This is instead of having <script tags in the index.html.
I'm not having much success ...
Dir :
webpack.config.js
node_modules/
vendor/aws-sdk.js
src/

webpack config 

```
var webpack = require('webpack');
module.exports = {
  devtool: 'source-map',
  entry: [
    'webpack-dev-server/client?http://0.0.0.0:3000',
    'webpack/hot/only-dev-server',
    './src/index.js'
  ],
  output: {
    publicPath: '/',
    path: __dirname + '/build',
    filename: 'bundle.js'
  },
  resolve:{
    modulesDirectories : ["node_modules", "vendor"]
  },
  module: {
    preLoaders: [
      {test: /\.js$/, loader: "eslint-loader", exclude: /node_modules/}
    ],
    loaders: [

      {test: /aws-sdk\.js$/, loader: "script"},

      {test: /\.js?$/, loaders: ['react-hot', 'babel?stage=1'], exclude: /(node_modules|vendor)/},

      {test: /\.css$/, loader: "style!css"},
      {
        test: /\.(png|jpg)$/,
        loader: 'url?limit=25000'
      },
      {test: /\.woff$/, loader: "url?limit=50000"}
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ]
};

```

I'm not too sure what reggae I should use for the aws-sdk? if this should also have the vendor prefix or not? I'v tried both ..
Ideally I want all js in the vendor dir so something like `.*vendor\/.*\.js$`

Any help would be much appreciated,
Cheers,
Stephen.

**Comment by michael-ciniawsky** [comment]
`expose-loader` || `imports-loader`
