### ISSUE TITLE
Can't get it to work at all with webpack dev server

### ISSUE THREAD

**Issue by SteveALee** [webpack-contrib/script-loader#16]
I tried loading 2 scripts one which uses a function defined in the other but it is always undefined. I tried in many places and using the debug I see the eval.call() and can step through the imported script but the values never stick. The Chrome tools indicate i'm in some sort of closure.

In case it helps here is my config - https://github.com/OpenDirective/brian/blob/master/webpack.config.js
And here are the scripts I tried to load - https://github.com/OpenDirective/brian/blob/master/src/assist.html . It's the second file that fails with BigInteger being undefined.

**Comment by michael-ciniawsky** [comment]
maybe related to #13

**Comment by r01010010** [comment]
same here

**Comment by michael-ciniawsky** [comment]
Please import logic like that as a module, this is not in the scope of this loader
