### ISSUE TITLE
Better example for new webpack folk

### ISSUE THREAD

**Issue by Vaccano** [webpack-contrib/script-loader#17]
The useage example is probably enough for webpack experts.  But it would be nice to know where in the config file that require statement is supposed to go.  (Just a suggestion.)

**Comment by horacio-giovine** [comment]
yes please, im trying to load https://logentries.com/doc/javascript/  
and i cant for the life of me get it to work

**Comment by k-funk** [comment]
I'm still quite confused. This seems to just replace the filename with a `require('path_on_disk/filename.js')`, which doesn't seem like it's executing anything in the global context unless I have something loaded in the browser that runs ajax to get those files.

**Comment by k-funk** [comment]
Looks like my issue was because I was also doing a `noParse` on the same directory, which stopped webpack from loading what it had `require`d. I'd still prefer to not parse these files, but still have them available/run in the global context—same as dumping them in via `<script>`s.

**Comment by tomccabe** [comment]
I wouldn't even call what's in the README an "example". Tells you absolutely nothing.

**Comment by pcompassion** [comment]
+1

**Comment by pcompassion** [comment]
I looked at the source, and I don't think it's meant to be used with external (https://) scripts.

**Comment by sunny-g** [comment]
@SpaceK33z

**Comment by SpaceK33z** [comment]
We are working on better documentation for all loaders. See https://github.com/webpack/webpack/issues/3195
