### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by freeman29** [webpack-contrib/script-loader#19]
Hi guys,

How can I fix this issue?

Thanks!

**Comment by adamasantares** [comment]
I got same error but with Twitter's typeahead.js :(

```js
import Bloodhound from 'script-loader!./typeahead/bloodhound.min.js';
import Typeahead from 'script-loader!./typeahead/typeahead.jquery.min.js';
```

```
module.exports = function(src) {
	if (typeof execScript !== "undefined")
		execScript(src);
	else
		eval.call(null, src);    // <== Uncaught TypeError: Cannot set property 'Bloodhound' of undefined
}
```

**Comment by michael-ciniawsky** [comment]
maybe related to #13

**Comment by michael-ciniawsky** [comment]
@adamasantares Form a first glance I think this is the cause too, if you havea workaround && time mind sending a quick PR 😛 ?

**Comment by adamasantares** [comment]
@michael-ciniawsky 

Hey, I found solution, check there https://github.com/twitter/typeahead.js/issues/1627

**Comment by michael-ciniawsky** [comment]
@adamasantares Thx very much I see 😛, closing since this is solve by using `imports-loader` instead for 'incompatible'  files
