### ISSUE TITLE
Cannot find module "script-loader!./test.js"

### ISSUE THREAD

**Issue by folmert** [webpack-contrib/script-loader#22]
`require("script-loader!./test.js");`

Console output:
> app.js:4 Uncaught Error: Cannot find module "script-loader!./test.js"
>     at webpackMissingModule (app.js:4)

I have test.js in the same dir with the original script. I'm using Webpack 2.

**Comment by michael-ciniawsky** [comment]
Please provide more info about your setup (the test file, `webpack.config.js`)
