### ISSUE TITLE
Is the example in source file or webpack.config.js file?

### ISSUE THREAD

**Issue by needforspeed** [webpack-contrib/script-loader#24]
Assume I have a lib.js and want to use it in file.js

Should I put it something like 
```javascript
require("script-loader!./lib.js");
```
in my file.js or in my webpack.config.js?

**Comment by michael-ciniawsky** [comment]
@needforspeed  if you don't config `script-loader` in `webpack.config.js` you need to reference it in the `require('script-loader!path/to/script.js') otherwise 

**file.js**
```js
require('path/to/script.exec.js')
```

**webpack.config.js**
```js
{ 
   test: /\.exec\.js$/, 
   use: [ { loader: 'script-loader' } ]
}
```

 is equivalent. I will refactor the docs...

**Comment by needforspeed** [comment]
@michael-ciniawsky Thank you. I figured out :)
