### ISSUE TITLE
Add "use strict" to every file included

### ISSUE THREAD

**Issue by mattiaocchiuto** [webpack-contrib/script-loader#25]
I'm using the script-loader (https://github.com/webpack-contrib/script-loader) to import some old libs. What I noticed is that at the top of the imported script is appended the "use strict" sentence but I dont want it.

Is there a way to disable this behaviour?

**Comment by wuxiandiejia** [comment]
@mattiaocchiuto Did you use babel-loader or es6's `import`? see [this](https://github.com/webpack/webpack/issues/2512).

**Comment by michael-ciniawsky** [comment]
`script-loader` does add anything here, see @wuxiandiejia comment please :)
