### ISSUE TITLE
SourceMaps

### ISSUE THREAD

**Issue by dfvalero** [webpack-contrib/script-loader#30]
I'm requiring a js file from my project, and I have devtools enabled with webpack. When I go to Chrome Devtools and I try to check the file, I only can see a compiled file like this:

module.exports = "[all-the-code]".

So... it's impossible to me to debug using devtools.

**Comment by jiaweihli** [comment]
This is actually [already implemented](https://github.com/webpack-contrib/script-loader/blob/master/index.js#L15) but hidden behind a debug flag.  If you're using webpack 2, one way to do this is add a plugin to the `plugins` array:

```js
    new webpack.LoaderOptionsPlugin({
      debug: true
    })
```

**Comment by jiaweihli** [comment]
I'm not sure why this isn't enabled by default 😕

**Comment by jimmymain** [comment]
I am using script-loader inline with webpack2.
I have the same problem.
I have tried both options, but it doesn't seem to work:

```
    // in webpack.js
    devtool: "sourcemap",
    plugins: [
        new webpack.LoaderOptionsPlugin({
              debug: true
            }),
```
My javascript file imports the relevant scripts inline as I only want to use `script-loader` for a few legacy scripts.
```
import "script-loader?sourceMap=true!../../sass/wrapkit-1.2/app/scripts/wrapkit/classie.js";
```
The result is inline `module.exports =` code without source maps that cannot be debugged.
```
module.exports = "(function(){\n  'use strict';\n  var WrapkitUtils = window.WrapkitUtils;\n\n  // slim scroll\n
```

any suggestions?

**Comment by Rouche** [comment]
@jimmymain Check my little example: https://github.com/Rouche/webpack-test

You can find the file with `Ctrl+P` pattern is like `script:///C:/[full path to file].js`
