### ISSUE TITLE
Scripts not being executed

### ISSUE THREAD

**Issue by r01010010** [webpack-contrib/script-loader#35]
I'm trying to upgrade from webpack 1 to 2 . Everything compiles, loads just fine apparently, but globally required variables are not available. 

The way I used to have it was, at some point in the entry flow, i had a lot of
```js
require('!!script-loader!./vendor/file1.js')
require('!!script-loader!./vendor/file2.js')
require('!!script-loader!./vendor/file3.js')
// ...
```
this configuration worked just fine, but with the upgrade, it seems scripts are not being executed

The webpack configuration entries are two, core and vendor:

```js
entry: {
      core: './app/javascripts/loader',
      vendor: [
        './app/javascripts/libraries',
        'backbone-redux',
        'brace-expansion'
      ]
```

If I put the require statements in the `javascripts/loader` file, it works (scripts are executed globally), but if I put them in `javascripts/libraries` files they don't.

**Env:**

- webpack v2
- webpack-dev-server v1.14
- script-loader v0.7

**Comment by michael-ciniawsky** [comment]
Please provide more info about your setup (e.g whole `webpack.config.js`)
