### ISSUE TITLE
Cannot use the script with Internet Explorer 11

### ISSUE THREAD

**Issue by alexandrujecan** [webpack-contrib/script-loader#36]
Hello,

I can't use this script in InternetExplorer 11 on an Apache HTTP Server.

I get an error when calling the method execScript() from addScripts.js:

module.exports = function(src) {
	if (typeof execScript !== "undefined")
		execScript(src);
	else
		eval.call(null, src);
}

The execScript() method is deprecated in IE 11.

Any solutions to this ?

**Comment by evilebottnawi** [comment]
@alexandrujecan it is only message about deprecated, should be work fine, just ignore this message because it is IE :imp:

**Comment by alexandrujecan** [comment]
@evilebottnawi 
No, it is not message about being deprecated.

It is simply not working:
"The process could not be continued  because of the following error: 80020101"

It points to the error:
In scripts.bundle.js which was autogenerated from addScripts.js.
It points to the line 7 from this file where the method execScript() is called.

**Comment by evilebottnawi** [comment]
@alexandrujecan your use latest version of IE 11?

**Comment by alexandrujecan** [comment]
@evilebottnawi 
IE version 11.0.9600.18655

**Comment by evilebottnawi** [comment]
@alexandrujecan i am not familiar with IE, it is new version?

**Comment by alexandrujecan** [comment]
@evilebottnawi 

No, it is not the newest.

**Comment by evilebottnawi** [comment]
@alexandrujecan can your try to update version to latest and testing again?

**Comment by alexandrujecan** [comment]
@evilebottnawi 
Unfortunately I can't. 
I have to make it work using this version

**Comment by evilebottnawi** [comment]
@alexandrujecan ok, let's try to fix it

**Comment by evilebottnawi** [comment]
@alexandrujecan can your create minimal reproducible test repo?

**Comment by alexandrujecan** [comment]
@evilebottnawi 

I am using Angular 2 with TypeScript
Node version = 6.10.3
NPM version = 3.10.10

I cannot open my application in Internet Explorer 11 which runs in compatibility mode.
I am using the script-loader.

When I debug I see that the problem is inside the scripts.bundle.js, which was generated into the dist folder.

The scripts.bundle.js file contains:
module.exports = function(src) {
	if (typeof execScript !== "undefined")
		execScript(src);
	else
		eval.call(null, src);
}

The error is thrown when attempting to call the "execScript(src)" method.

**Comment by jcjolley** [comment]
I too am facing this issue, with Angular 4.3.4 and Typescript 2.4

**Comment by jcjolley** [comment]
@alexandrujecan 
This happened for me when trying to load a version of popper.js that didn't follow the UMD format.
When I switched to their UMD version, the error went away.
