### ISSUE TITLE
Using sourceMaps with script-loader

### ISSUE THREAD

**Issue by pweaver** [webpack-contrib/script-loader#38]
We are using script-loader to load pre minified files. These minified files usually also have source maps. script-loader should also specify where to find source maps.

**Comment by evilebottnawi** [comment]
@pweaver please describe more information, btw maybe your want https://github.com/webpack-contrib/source-map-loader

**Comment by pweaver** [comment]
Yes, we are using source-map-loader. I think the problem is that the minified files don't have a sourceMapUrl comment embeded in the minified version so we need to figure out how to add one.

**Comment by pweaver** [comment]
Actually, even with a source map url, source-map-loader is not passing through sourcemaps.

See underscore-min.js in the underscore node library. Or jquery.min.js in the query library for and example without a sourceMapURL.

**Comment by evilebottnawi** [comment]
@pweaver can your create minimum reproducible test repo, this saves time, thanks!

**Comment by pweaver** [comment]
https://github.com/pweaver/source-map-test

**Comment by evilebottnawi** [comment]
@pweaver thanks

**Comment by pweaver** [comment]
I did a little poking around. source-map-loader is loading the source maps when a sourceMapURL comment is present. It just isn't usefully passing them on to everything else and I haven't figure out enough about webpack to understand why.

**Comment by michael-ciniawsky** [comment]
Tracking Issue #30 && PR #31
