### ISSUE TITLE
[Script Loader]  import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by reficedev** [webpack-contrib/script-loader#42]
Hi, 

I get this message on my test webpage.
[Script Loader]  import declarations may only appear at top level of a module

Can you see why ?
[webpack+script-loader.zip](https://github.com/webpack-contrib/script-loader/files/1320386/webpack.script-loader.zip)

I'm using webpack 5.3.0 + node 8.5.0 

thanks in advance

**Comment by michael-ciniawsky** [comment]
You need the [`expose-loader`](https://github.com/webpack-contrib/expose-loader) || [`imports-loader`](https://github.com/webpack-contrib/imports-loader) for your purpose. Also bundling them directly without anything else might be worth a try :)
