### ISSUE TITLE
Error: require is not defined

### ISSUE THREAD

**Issue by rebolyte** [webpack-contrib/script-loader#48]
This seems like a problem I shouldn't be having, but that's the error I keep running into with this loader. I've added a stripped-down config and the generated bundle in [this gist](https://gist.github.com/rebolyte/8e6c65bd50b043ac921206c5b9a65c73), and it's easy to see that the call to `require` for each module is going to fail.

My situation: I have a bunch of legacy JS (no modules, expecting to run in `window`) that just needs to be bundled in the correct order and minified. Nothing else. All I need is for the scripts to be loaded in the page like so:

```
<script src="manifest.js"></script>
<script src="legacyJS.[hash].js"></script>
```

Correct me if I'm wrong, but this loader seems like the answer to this problem. How can I make the `require` function get passed to each module in the output? It looks like the output isn't fully evaluated or something, since I want the contents of those files passed through the loaders, not the string of loaders+filepath. I see in the brief example in the readme that the generated modules are still meant to be imported, but I don't want that here. What am I doing wrong? Am I so confused that this loader isn't the one I want?

Many thanks.

**Comment by michael-ciniawsky** [comment]
Can you show code from one of the `widgets` aswell please. I'm not 💯  yet 😛 
Can could you try with just entry and `require` all widgets there ?

**Comment by rebolyte** [comment]
Thanks for the quick response. I figured it out: `noParse` was causing my issues. Removing it correctly  passes `__webpack_require__` to each module. I had added it based on reading [this](https://webpack.js.org/guides/shimming/#other-utilities), which I guess doesn't work when I do have multiple "modules" that need to run in a specific order, rather than just one file.
