### ISSUE TITLE
[Karma] Bundled file works in browser but can't be loaded in Karma

### ISSUE THREAD

**Issue by whtrbit** [webpack-contrib/script-loader#52]
Hey guys,
my problem occurs in AngularJS 1.3 app. I have one JS file bundled with script-loader. Everything works great in the browser - app works the same as before. However I have a problem with loading this file into Karma config. I've reduced my config files so now it looks like this:

```
module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine'],
        files: [
            'app/app.bundle.js'
        ],
        // the rest goes beneath but is not relevant to this issue
    });
};
```

Like I said there is no problem in the app but Karma throws an error:
`
Uncaught Error: [$injector:modulerr] Failed to instantiate module edenred due to:
Error: [$injector:modulerr] Failed to instantiate module expenseClaim due to:
Error: [$injector:unpr] Unknown provider: USER_TYPE
`

So simply it has a problem with some dependencies - USER_TYPE is a constant in my app.
That the line it breaks - note that it doesn't on STATES_EXPENSE_PROFILES or $stateProvider.
`
.config(function ($stateProvider, STATES_EXPENSE_PROFILES, USER_TYPE) {
`

I'm using webpack@3.5.6, karma@1.7.0.

I'd appreciate any clues,
best, G.

**Comment by evilebottnawi** [comment]
Should be solve in `webpack@4` and latest karma-loader, please test and feel free to open new issue if problem still exists, also please provide minimum reproducible test repo, thanks!
