### ISSUE TITLE
Using script-loader seems to lead to a different `[chunkhash]` being generated each time

### ISSUE THREAD

**Issue by jakub-g** [webpack-contrib/script-loader#56]
Hello,

First of all, I know that `[chunkhash]` is not the best idea for long term caching, and it's better to use a plugin that creates content-hash, which we will probably do very soon.
Nevertheless I wanted to report the issue, even if only to help some other people who are investigating similar issues.

----

So, we're using webpack 3.x for now, and we have two external scripts, let's call them `foo` and `bar` that are loaded through script-loader `0.7.1` like this:

```
  loadFooLib() {
    return import(/* webpackChunkName: 'foobar' */ 'script-loader!foo')
  },
```
(with `foo$: 'html/vendor/foo/Foo'` in webpack resolve config).

When we run the build twice after some time, without any code change in `foo` or `bar` (for example, a non-code commit), this often* results in the `chunkhash` change for `foo` and `bar` (the chunks that go through `script-loader`), and no output change for the other chunks -- and this in turn means that the `manifest` chunk has to be regenerated as well.

*often = not always, and it's happening a lot on our Linux build machines, but I could not reproduce so far on Windows

Looking at the code, things look very simple and there seems to be no obvious reason for `script-loader` to generate different `chunkhash` each time. 

@sokra Do you have any ideas? Is this kind of issue more likely to be on the plugin side, or webpack side?

**Comment by jakub-g** [comment]
Well actually this looks suspicious a bit:
https://github.com/webpack-contrib/script-loader/blob/master/index.js#L7-L11

**Comment by michael-ciniawsky** [comment]
It's a bit 'old' but maybe it helps https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31, otherwise I'm sry but it is very hard to exactly tell where/what in **your** application currently causes the `[chunkhash]` to change

**Comment by jakub-g** [comment]
FWIW we've migrated do webpack 4 and `contenthash` and this still happens (only for stuff loaded with `script-loader`).
Will need to deep dive into it to figure out what's exactly happening.

**Comment by onlybye** [comment]
> Update: from what I've noticed in the recent weeks, the issue actually happens also for some new chunks in our project that are not loaded via `script-loader`. **The issue is not script-loader** then (probably).
> 
> [webpack/webpack#7179 (comment)](https://github.com/webpack/webpack/issues/7179#issuecomment-449563879)
@jakub-g we have alse met this problem, have you solved?

**Comment by jakub-g** [comment]
> we have also met this problem, have you solved?

nope, not yet unfortunately

**Comment by jakub-g** [comment]
@onlybye see #49 #60 and https://medium.com/@the_teacher/webpack-different-assets-hashes-on-different-machines-the-problem-the-solution-ec6383983b99
