### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by ryanburnette** [webpack-contrib/script-loader#57]
Let's say my bundle source looks something like this...

```javascript
require('script-loader!polyfill.js')
require('app.js')
```

For the cases where `polyfill.js` is necessary, can I rely on it being called before anything in `app.js`?

- webpack 4.17.2
- script-loader 0.7.2

**Comment by michael-ciniawsky** [comment]
I think so but wouldn't rely on it, a separate `<script src="polyfills.js">` (in the HTML Template) or using `babel-loader` + `babel-runtime` is the safest approach here

**Comment by ryanburnette** [comment]
@michael-ciniawsky Based on some sanity checks I performed, it was reliable, but out of an abundance of caution, I moved my polyfills to a `polyfills.js` file as you already suggested. Thanks for getting back to me.
