### ISSUE TITLE
Error in IE 11

### ISSUE THREAD

**Issue by levipadre** [webpack-contrib/script-loader#58]
There is an error in IE11. The site doesn't work except when the dev toolbar is open. In that case I see and error: "`[Script Loader] SyntaxError: Syntax error`".

In my app.js file I'm using script-loader like this:
```
require('!!script-loader!./vendor/foo.js')
require('!!script-loader!jbar.js')
```

Any advice?

**Comment by michael-ciniawsky** [comment]
Try 

```
require('script-loader!./file.js')
```

and otherwise one of your files seems to contain a (valid) `{SyntaxError}` somewhere as the unhelpful `err.message` suggest
